<a href="https://colab.research.google.com/github/VaibhavDS19/ML-DSC/blob/master/DataHandling/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array( [1,2,3,4,5] )
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array( [ [1,2,3],[3,4,5] ] ) 

In [12]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print( "Shape: ",a1.shape )
print("Number of dimensions: ", a1.ndim)
print("Size: ", a1.size)
print("Type: ", a1.dtype)

Shape:  (5,)
Number of dimensions:  1
Size:  5
Type:  int64


In [13]:
# Attributes of 2-dimensional array
print( "Shape: ",a2.shape )
print("Number of dimensions: ", a2.ndim)
print("Size: ", a2.size)
print("Type: ", a2.dtype)

Shape:  (2, 3)
Number of dimensions:  2
Size:  6
Type:  int64


In [23]:
# Create an array of shape (5, 5) with only ones
a3 = np.ones( (5,5), np.int64)
a3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# Create an array of shape (3, 3, 5) with only zeros
a4 = np.zeros( (3,3,5), np.int64)
a4

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [25]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(0, 10, (7,2), np.int64 )
a5

array([[5, 4],
       [7, 6],
       [3, 3],
       [2, 6],
       [0, 6],
       [8, 0],
       [3, 1]])

In [27]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.rand( 3,5 )
a6

array([[0.17322465, 0.40512076, 0.10539308, 0.9027346 , 0.80337513],
       [0.0194811 , 0.27549704, 0.06440652, 0.77042545, 0.42590259],
       [0.48217174, 0.14923572, 0.07277687, 0.14639931, 0.36973917]])

In [28]:
# Create an array of normally distributed random numbers
a7 = np.random.randn(5)
a7

array([-0.10793039,  1.24929159,  0.77123828, -1.29294015,  0.7804747 ])

In [34]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a8 = np.random.rand(4,6)
a8

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [33]:
# Copy the code from the cell above and run it again
np.random.seed(42)
a9 = np.random.rand(4,6)
a9

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [36]:
# Find the 0'th index of the latest array you created
print(a9[0][0])

0.3745401188473625


In [41]:
# Get the first 2 rows of latest array you created
r1 = a9[0]
r2 = a9[1]
print( r1,"\n", r2 )

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452] 
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]


In [44]:
# Get the first 2 values of the first 2 rows of the latest array
r1v1 = r1[0]
r2v1 = r2[0]
print(r1v1,"\n",r2v1)

0.3745401188473625 
 0.05808361216819946


In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables


In [ ]:
# Add the two arrays together


In [ ]:
# Create another array of ones of shape (5, 3)


In [ ]:
# Try add the array of ones and the other most recent array together # You can anticipate an error


In [ ]:
# Do the same operation you just did but this time with a transpose on one array


In [ ]:
# Take the latest array to the power of 2 using the python way


In [ ]:
# Do the same thing with numpy way


In [ ]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()


In [ ]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)


In [ ]:
# Perform a dot product on the two newest arrays you created


In [ ]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)


In [ ]:
# Perform a hadamard product on the two newest arrays you created


In [ ]:
# Perform a dot product on the two newest arrays you created # Error anticipated


In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both


In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables


In [ ]:
# Compare the two arrays with '>', '<=' and '==' 


In [ ]:
# Sort one of the arrays you just created in ascending order


In [ ]:
# Sort the indexes of one of the arrays you just created


In [ ]:
# Find the index with the maximum value in one of the arrays you've created


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100


In [ ]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created


In [ ]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
